---
- name: Set Idea type to Community
  become: false
  when: intellij_license is not defined
  set_fact:
    intellij_idea_type: IIC
    intellij_idea_type_short: IC
  changed_when: false
- name: Set Idea type to Ultimate
  become: false
  when: intellij_license is defined
  set_fact:
    intellij_idea_type: IIU
    intellij_idea_type_short: IU
  changed_when: false

- name: Get release info
  become: false
  uri:
    url: "https://data.services.jetbrains.com/products/releases?code={{ intellij_idea_type }}&latest=true&type=release"
    return_content: yes
  register: release_info
  changed_when: false

- name: Register Facts
  become: false
  set_fact:
    intellij_major_version: "{{ release_info.json[intellij_idea_type].0.majorVersion }}"
    intellij_version: "{{ release_info.json[intellij_idea_type].0.version }}"
    intellij_build: "{{ release_info.json[intellij_idea_type].0.build }}"
    intellij_download_url: "{{ release_info.json[intellij_idea_type].0.downloads.linux.link }}"
  changed_when: false

- name: Register Tarball Name as Fact
  become: false
  set_fact:
    intellij_tarball_name: "{{ intellij_download_url | basename }}"
  changed_when: false

- name: Set extracted folder name
  become: false
  set_fact:
    intellij_extracted_folder: "idea-{{ intellij_idea_type_short }}-{{ intellij_build }}"
  changed_when: false
